package cmds

import (
	"errors"
	"os"

	"github.com/hitzhangjie/tinydbg/service/debugger"
	"github.com/spf13/cobra"
)

var coreCommand = &cobra.Command{
	Use:   "core <executable> <core>",
	Short: "Examine a core dump.",
	Long: `Examine a core dump (only supports linux and windows core dumps).

The core command will open the specified core file and the associated
executable and let you examine the state of the process when the
core dump was taken.

Currently supports linux/amd64 and linux/arm64 core files, windows/amd64 minidumps and core files generated by Delve's 'dump' command.`,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		if len(args) != 2 {
			return errors.New("you must provide a core file and an executable")
		}
		return nil
	},
	Run: coreCmd,
	ValidArgsFunction: func(cmd *cobra.Command, args []string, toComplete string) ([]string, cobra.ShellCompDirective) {
		if len(args) > 2 {
			return nil, cobra.ShellCompDirectiveNoFileComp
		}
		return nil, cobra.ShellCompDirectiveDefault
	},
}

func init() {
	// -c is unused and exists so delve can be used with coredumpctl
	core := false
	coreCommand.Flags().BoolVarP(&core, "core", "c", false, "")
	coreCommand.Flags().MarkHidden("core")
}

func coreCmd(_ *cobra.Command, args []string) {
	os.Exit(execute(0, []string{args[0]}, conf, args[1], debugger.ExecutingOther, args, buildFlags))
}
