@startuml

hide footbox

actor User
participant "Debugger Backend" as BE
participant "Tracee" as TP

User -> BE : input `godbg attach <pid>`

activate User #ff0000
activate BE #ff0000

BE -> BE: d := debugger.New(pid,...)\nd.Attach(pid,...)
activate BE #ffff00
deactivate BE

BE -> TP: syscall `ptrace(PTRACE_ATTACH, pid, nil, nil)`
activate BE #ffff00
activate TP #ff0000
TP --> TP: kernel process PTRACE syscall:\n1. task_struct.ptrace = TRACED\n2. send SIGTRAP to process
activate TP #ffff00
deactivate TP
TP --> BE: ptrace returns
deactivate BE

BE --> TP: wait4(pid,status):\n1. ptracer `interruptible sleep`\n2. added to waiting list of tracee's state changed\n3. will be woken up by SIGCHILD
activate BE #ffff00

activate TP #ffff00

TP --> TP: SIGTRAP handler: \n1. stop the process\n2. send SIGCHLD to ptracer, \n    notify child process state changed
TP --> BE: send SIGCHLD to ptracer \nps: but SIGCHLD may be not generated ❌,\n     so __wake_up_parent(tsk, ptracer) called

TP --> TP: 3. __wake_up_parent(tsk, ptracer) called
deactivate TP

activate BE #00ffff
BE --> BE: 1. wake up ptracer\n2. ptracer `interruptible sleep` to `runnable`\n3. scheduler shedules ptracer\n4. wait4(...) returns\n\nps: even if SIGCHLD not generated,\n__wake_up_parent(...) will wake up the ptracer,\n both of them could wake up ptracer.
deactivate BE

deactivate TP

TP --> BE: wait4 returns
deactivate BE

deactivate TP

BE --> User: attach ok
deactivate BE

deactivate User

@enduml